### ISSUE TITLE
utf8 decode issue

### ISSUE THREAD

**Issue by matthewfischer** [SUSE-Cloud/keystone-hybrid-backend#11]
I'm on a fork of your code, but it's essentially the same. When I upgraded my nodes from Icehouse 2014.1.1 to 2014.1.2.1 (Ubuntu) I had auth failures with the identity module for LDAP based interactions. I verified my ldap config and connectivity. I ended up tracking the cause down to a large change in keystone/common/core/ldap.py that was backported. This change causes a UnicodeDecodeError exception to bubble up to the driver.

This is the change in master:

commit cbf805161b84f13f459a19bfd46220c4f298b264
Author: John Dennis jdennis@redhat.com
Date:   Sat Mar 22 13:54:04 2014 -0400

```
Properly handle unicode & utf-8 in LDAP
```

The backport is this (from Ubuntu changelog)
 [935fd60] Encode/Decode LDAP parameters to/from UTF-8

So far I've not made much progress into this except to see that the call to _id_to_dn is failing even though the bind looks okay to me. I don't have any great theories except that the search is returning something strange from my LDAP box (although I have no evidence of this yet). I didn't have much time to dig into it today. Has anyone else seen this with Icehouse 1.2.1?

(Note I managed to not save the error out to a file and have since re-done my node with 1.1, sorry for that)

**Comment by iartarisi** [comment]
Matthew, from what you're saying this issue seems to be specific to the LDAP backend and not related to the hybrid backend. Is this correct?

**Comment by matthewfischer** [comment]
I've been unable to confirm that as I've been on holiday, I'll find out
more next week, starting with the generic LDAP backend. I can only test
read operations against it but that should be enough.

**Comment by matthewfischer** [comment]
When I use the basic LDAP driver I'm not having this issue. I did have to downgrade python-ldap to 2.3 or I ran into a strange error message related to paged queries. I'll dig into this more and update tonight or tomorrow.

**Comment by sergio97** [comment]
I've tested applying the patch from https://bugs.launchpad.net/keystone/+bug/1364521 to the ldap identity backend and it resolved this issue with no change to the hybrid driver. Did this using python-ldap 2.4.10.

**Comment by matthewfischer** [comment]
More testing results..

I decided last night to ditch my fork and switch to your code, except I commented out the listing of LDAP users (we have way too many).  I tested it fine with Icehouse 1.1, but when I upgraded the keystone server and python-keystoneclient to 1.2.1, I get errors. This is what I'm seeing now:

'utf8' codec can't decode byte 0x80 in position 3: invalid start byte
2014-09-04 15:19:49.835 9270 WARNING keystone.common.wsgi [-] Authorization failed. The request you have made requires authentication. from 1.2.3.4

**Comment by matthewfischer** [comment]
Note, I did not have this issue with the basic LDAP driver.

**Comment by matthewfischer** [comment]
It looks like the bug fix you posted has spawned a bunch of other bugs:

https://bugs.launchpad.net/keystone/+bug/1358330
and
https://bugs.launchpad.net/keystone/+bug/1364521

**Comment by matthewfischer** [comment]
Some updates on this. It looks like the error is due to some odd data in my LDAP attrs that the new ldap2py() function cannot decode. Based on what I've seen from other bugs I'm not the only one. However I do not believe this is related to this driver specifically. If you want to leave this open, I'll update it when I have a resolution for other people or we can close it since this is really an upstream issue.

**Comment by iartarisi** [comment]
@matthewfischer agreed. I also believe this bug is not in the hybrid backend and would be better tracked upstream where it would also probably have more visibility.
