### ISSUE TITLE
any use for debian packaging?

### ISSUE THREAD

**Issue by matthewfischer** [SUSE-Cloud/keystone-hybrid-backend#13]
My fork has some debian packaging in it which I've been using, but I know this is driven by SUSE. Is there any value in me doing a PR for the debian stuff into here?

**Comment by iartarisi** [comment]
I'm not a fan of holding distro package files in the same repository as the sources. Ideally these should be maintained on the distro's side. In SUSE's case, for example, these are at: https://build.opensuse.org/package/show/Cloud:OpenStack:Icehouse/openstack-keystone

I think a better place for the debian ones would be the debian repositories or some PPA.
