### ISSUE TITLE
Authentication success when password is None

### ISSUE THREAD

**Issue by cbartz** [SUSE-Cloud/keystone-hybrid-backend#16]
Dear all,

I believe that there is a serious security issue in the method authenticate of the hybrid_identity module . When a user is not found in sql and the password is None or '', the authentication will succeed in every case, because get_connection internally does not call simple_bind when the password is not set, and thus raises no exception in this case.

Therefore, get_connection should not be called when the password is not set.

**Comment by iartarisi** [comment]
Thanks a lot for the bug report, @cbartz! I pushed a commit which should fix the bug.
