### ISSUE TITLE
sql _get_user function changed

### ISSUE THREAD

**Issue by digglife** [SUSE-Cloud/keystone-hybrid-backend#2]
get refs from sql session.
def _get_use(session,user_id)

https://github.com/openstack/keystone/commit/8d2b8e6457d5ae0ed1136091cb8c143a96abd614#diff-d36d696b43e6991c5e56b7085e3ca411L171

**Comment by iartarisi** [comment]
Hey,

I've created a new havana branch which passes the session as a first parameter to _get_user calls: https://github.com/SUSE-Cloud/keystone-hybrid-backend/tree/havana . Could you check that out?

Otherwise, could you reopen this issue and be more specific about what the problem is?

Thanks.

**Comment by digglife** [comment]
Sorry I didn't notice your update. =P Thanks!
