### ISSUE TITLE
Using Unscoped Token to get a Scoped Token Fails for LDAP Users

### ISSUE THREAD

**Issue by sergio97** [SUSE-Cloud/keystone-hybrid-backend#20]
When an LDAP user uses an unscoped keystone token and a project name to get a scoped token, keystone returns HTTP 500 and logs this exception:

> [-] 'domain_id'
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/keystone/common/wsgi.py", line 212, in **call**
>     result = method(context, **params)
>   File "/usr/lib/python2.7/dist-packages/keystone/token/controllers.py", line 101, in authenticate
>     core.validate_auth_info(self, user_ref, tenant_ref)
>   File "/usr/lib/python2.7/dist-packages/keystone/token/core.py", line 78, in validate_auth_info
>     user_ref['domain_id'])
> KeyError: 'domain_id'

If I repeat this for an SQL user, it works as expected.

To repeat this issue:

``` python
from novaclient.v1_1 import client as nc
from keystoneclient.v2_0 import client as kc
from keystoneclient.auth.identity import v2
from keystoneclient import session as sess

username = "admin"
password = "password"
project_name = "admin"
auth_url = "http://127.0.0.1:5000/v2.0/"

auth = v2.Password(auth_url=auth_url, username=username, password=password)
session = sess.Session(auth=auth)
ks = kc.Client(session=session)
ks.users.list() # fails because unscoped

auth_scoped = v2.Password(auth_url=auth_url, username=username, password=password, tenant_name=project_name)
session_scoped = sess.Session(auth=auth_scoped)
ks_full = kc.Client(session=session_scoped)
ks_full.users.list() # works

auth_from_token = v2.Token(auth_url=auth_url, token=session.get_token(), tenant_name=project_name)
session_from_token = sess.Session(auth=auth_from_token)
ksfk = kc.Client(session=session_from_token)
ksfk.users.list() # Works for SQL users, fails for LDAP users.
```

Repeat this code for an LDAP user and the last line will fail with:

> keystoneclient.openstack.common.apiclient.exceptions.AuthorizationFailure: Authentication failure: An unexpected error prevented the server from fulfilling your request. (HTTP 500)

**Comment by sergio97** [comment]
I have a fix for this issue in my fork https://github.com/breqwatr/keystone-hybrid-backend/tree/icehouse-issue-20
So far it doesn't break anything, but I'm going to test for a few more days just in case.

**Comment by sergio97** [comment]
Closed issue by accident. Re-opened

**Comment by rhafer** [comment]
Fix was merged. Closing.

**Comment by sergio97** [comment]
Thanks rhafer
