### ISSUE TITLE
move constants from hybrid_assignment to keystone.conf

### ISSUE THREAD

**Issue by iartarisi** [SUSE-Cloud/keystone-hybrid-backend#3]
It would be nice to have the constants from the hybrid assignment backend in keystone.conf in the [assignment] section so the user doesn't have to edit two files when installing and we don't hold configuration options in /usr/lib .

**Comment by iartarisi** [comment]
I'm not sure this would outweigh the benefit of (currently) having only one file to install.

**Comment by rhafer** [comment]
AFAICS this was implemented as part of: https://github.com/SUSE-Cloud/keystone-hybrid-backend/pull/15

Closing
