### ISSUE TITLE
'User' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by hfrenzel** [SUSE-Cloud/keystone-hybrid-backend#9]
While using hybrid_identity.py, the following error occured on executing 'keystone user-get':

ERROR keystone.common.wsgi [-] 'User' object has no attribute 'to_dict'
TRACE keystone.common.wsgi Traceback (most recent call last):
TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/common/wsgi.py", line 207, in **call**
TRACE keystone.common.wsgi     result = method(context, *_params)
TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/assignment/controllers.py", line 77, in get_projects_for_token
TRACE keystone.common.wsgi     self.assignment_api.list_projects_for_user(user_ref['id']))
TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/assignment/core.py", line 289, in list_projects_for_user
TRACE keystone.common.wsgi     x in self.identity_api.list_groups_for_user(user_id)]
TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/common/manager.py", line 47, in wrapper
TRACE keystone.common.wsgi     return f(self, *args, *_kwargs)
TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/identity/core.py", line 189, in wrapper
TRACE keystone.common.wsgi     return f(self, _args, *_kwargs)
TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/identity/core.py", line 447, in list_groups_for_user
TRACE keystone.common.wsgi     user_id, hints or driver_hints.Hints())
TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/identity/backends/sql.py", line 220, in list_groups_for_user
TRACE keystone.common.wsgi     self.get_user(user_id)
TRACE keystone.common.wsgi   File "/usr/lib/python2.6/site-packages/keystone/identity/backends/hybrid_identity.py", line 99, in get_user
TRACE keystone.common.wsgi     return identity.filter_user(self._get_user(session, user_id).to_dict())
TRACE keystone.common.wsgi AttributeError: 'User' object has no attribute 'to_dict'
TRACE keystone.common.wsgi

b/r
H.

**Comment by iartarisi** [comment]
Hi,

I just tried the latest code now and I can't reproduce it. Both `user-get` and `user-list` commands work fine here for both LDAP and SQL users.

Are you running the latest code? Does the git branch match the openstack release you are  using? I'm assuming Icehouse? (there are also branches for older versions)

**Comment by hfrenzel** [comment]
On the server:
$ rpm -qa |grep keystone
openstack-keystone-2014.1.1-1.el6.noarch
python-keystoneclient-0.9.0-1.el6.noarch
python-keystone-2014.1.1-1.el6.noarch

On the client:
$ dpkg -l | grep keystone 
ii  python-keystoneclient                 1:0.9.0-1                        all          client library for the OpenStack Keystone API

With just keystone.identity.backends.ldap.Identity, the user info is retrieved, but not with hybrid_identity.

b/r
Hendrik

PS:
- user-get for SQL account:
  $ keystone user-get admin
  +----------+----------------------------------+
  | Property |              Value               |
  +----------+----------------------------------+
  |  email   |                                  |
  | enabled  |               True               |
  |    id    | ed566648715a4af7940acdc3a9b1d737 |
  |   name   |              admin               |
  | username |              admin               |
  +----------+----------------------------------+
- user-get for ldap account:
  $ keystone user-get ttest
  An unexpected error prevented the server from fulfilling your request. (HTTP 500)

**Comment by iartarisi** [comment]
Ah, I think I found the problem. I broke this yesterday while trying to add some tests. Could you try the `devel` branch and let me know how it goes?

**Comment by hfrenzel** [comment]
It does not work with devel branch, but now in line 105. If i drop the .to_dict() in this line, it works.

b/r

**Comment by iartarisi** [comment]
Argh, right. I missed that. 

Thanks a lot for reporting this issue!
